name: ZolaDeploy

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-dev:  
    runs-on: ubuntu-latest
    environment:
      name: DEV
      url: "https://alanbarros.github.io/alanzola"
    steps:
      - uses: actions/checkout@v2
      # Execute the Zola Deploy
      - name: Zola Deploy (With local binary)
        run: ./.github/scripts/deploy_zola.sh
        env: 
          TOKEN: ${{ secrets.TOKEN }}
          PAGES_BRANCH: gh-pages
          REPO_GITHUB_IO: "alanbarros/alanzola"
          ZOLA_BASE_URL: https://alanbarros.github.io/alanzola

  build-prod:  
    runs-on: ubuntu-latest
    environment:
      name: PROD
      url: "https://alanbarros.github.io"
    needs: build-dev
    steps:
      - uses: actions/checkout@v2
      # Execute the Zola Deploy
      - name: Zola Deploy (With local binary)
        run: ./.github/scripts/deploy_zola.sh
        env: 
          TOKEN: ${{ secrets.TOKEN }}
          PAGES_BRANCH: gh-pages
          REPO_GITHUB_IO: "alanbarros/alanbarros.github.io"
          ZOLA_BASE_URL: https://alanbarros.github.io
